from pydantic import BaseModel, Field

class PromptRequest(BaseModel):
    """The input state for the environment."""
    base_query: str = Field(..., description="The forbidden task the target LLM should refuse.")
    adversarial_prefix: str = Field(..., description="The generated tokens trying to break the target.")

    @property
    def full_prompt(self) -> str:
        return f"{self.adversarial_prefix} {self.base_query}".strip()

class TargetResponse(BaseModel):
    """The output from the frozen target model."""
    request: PromptRequest
    completion: str = Field(..., description="The raw text generated by the target LLM.")

class RewardSignal(BaseModel):
    """The evaluated scores from toxicity evaluator and perplexity evaluator."""
    toxicity_score: float = Field(..., ge=0.0, le=1.0)
    perplexity_score: float = Field(..., ge=0.0)
    total_reward: float = Field(..., description="The combined math: (alpha * tox) - (beta * perp)")

class RLExperience(BaseModel):
    """A single complete trajectory to be stored in the GRPO buffer."""
    request: PromptRequest
    response: TargetResponse
    reward: RewardSignal
    
    prefix_tensor: list[int] | None = Field(default=None, description="Token IDs of the prefix")
    log_probs: list[float] | None = Field(default=None, description="Log probabilities of generated tokens")